products = [
    {"name": "ELFLIQ 10ML MEDIUM Apple Peach", "price": 150},
    {"name": "ELFLIQ 10ML MEDIUM Blueberry", "price": 150},
    {"name": "ELFLIQ 10ML MEDIUM Cotton Candy Ice", "price": 150},
    {"name": "ELFLIQ 10ML MEDIUM Cream Tobacco", "price": 150},
    {"name": "ELFLIQ 10ML MEDIUM Kiwi Passion Fruit Guava", "price": 150},
    {"name": "ELFLIQ 10ML MEDIUM Pink Grapefruit", "price": 150},
    {"name": "ELFLIQ 10ML MEDIUM Pink Lemonade", "price": 150},
    {"name": "ELFLIQ 10ML MEDIUM Spearmint", "price": 150},
    {"name": "ELFLIQ 10ML MEDIUM Watermelon", "price": 150},
    {"name": "BLACK JACK HARD Cherry Tobacco", "price": 335},
    {"name": "BLACK JACK HARD Cigarette Tobacco", "price": 335},
    {"name": "BLACK JACK HARD Coffee Tobacco", "price": 335},
    {"name": "BLACK JACK HARD Grape Tobacco", "price": 335},
    {"name": "BLACK JACK HARD Peppery Tobacco", "price": 335},
    {"name": "BLACK JACK HARD Pistachio Tobacco", "price": 335},
    {"name": "BLACK JACK HARD Strong Tobacco", "price": 335},
    {"name": "BLACK JACK HARD Sweet Tobacco", "price": 335},
    {"name": "BLACK JACK HARD Western Tobacco", "price": 335},
    {"name": "BRYZGI HARD Собираем Миксом", "price": 330},
    {"name": "BRYZGI MEDIUM Собираем Миксом", "price": 330},
    {"name": "Adventure Time HARD Банан Клубника", "price": 300},
    {"name": "Adventure Time HARD Виноград Яблоко", "price": 300},
    {"name": "Adventure Time HARD Грушевый Лимонад", "price": 300},
    {"name": "Adventure Time HARD Киви Маракуйя", "price": 300},
    {"name": "Adventure Time HARD Малина Апельсин", "price": 300},
    {"name": "Adventure Time HARD Манго Персик", "price": 300},
    {"name": "Adventure Time HARD Скитлс Вишня Лайм", "price": 300},
    {"name": "Adventure Time HARD Фруттелла Черника Малина", "price": 300},
    {"name": "COUNTER STRIKE HARD Арбузный ХЕДШОТ", "price": 360},
    {"name": "COUNTER STRIKE HARD Виноградный ЧИТЕР", "price": 360},
    {"name": "COUNTER STRIKE HARD Земляничный DEAGL", "price": 360},
    {"name": "COUNTER STRIKE HARD Клубничный КЕРАМБИТ", "price": 360},
    {"name": "COUNTER STRIKE HARD Малиновый АК-47", "price": 360},
    {"name": "COUNTER STRIKE HARD Персиковая М-КА", "price": 360},
    {"name": "COUNTER STRIKE HARD Тропический ВЗРЫВ", "price": 360},
    {"name": "COUNTER STRIKE HARD Энергетический FLASH", "price": 360},
    {"name": "COUNTER STRIKE HARD Яблочный ДЕФЬЮЗ", "price": 360},
    {"name": "COUNTER STRIKE HARD Ягодный AWP", "price": 360},
    {"name": "HOOLI DOOLI LIGHT Абрикосовое Манго", "price": 280},
    {"name": "HOOLI DOOLI LIGHT Ананас", "price": 280},
    {"name": "HOOLI DOOLI LIGHT Банановое Яблоко", "price": 280},
    {"name": "HOOLI DOOLI LIGHT Вишнёвая Смородина", "price": 280},
    {"name": "HOOLI DOOLI LIGHT Лимонад Тайга", "price": 280},
    {"name": "HOOLI DOOLI LIGHT Лимонный Чай", "price": 280},
    {"name": "HOOLI DOOLI LIGHT Малиновая Дыня", "price": 280},
    {"name": "HOOLI DOOLI LIGHT Малиновый Чай", "price": 280},
    {"name": "HOOLI DOOLI LIGHT Мятная Смородина с Малиной", "price": 280},
    {"name": "HOOLI DOOLI LIGHT Мятный Арбуз", "price": 280},
    {"name": "HOOLI DOOLI LIGHT Яблочное Киви", "price": 280},
    {"name": "HOT SPOT Газировка Байкал", "price": 350},
    {"name": "HOT SPOT Газировка Барбарис", "price": 350},
    {"name": "HOT SPOT Газировка Дюшес", "price": 350},
    {"name": "HOT SPOT Газировка Крем-Сода", "price": 350},
    {"name": "HOT SPOT Газировка Тархун", "price": 350},
    {"name": "HOT SPOT Клубничное Мороженое", "price": 350},
    {"name": "HOT SPOT Лимонное Мороженое", "price": 350},
    {"name": "HOT SPOT Малиновое Мороженое", "price": 350},
    {"name": "HOT SPOT Мороженое с Киви", "price": 350},
    {"name": "HOT SPOT Освежающее Манго", "price": 350},
    {"name": "HOT SPOT Освежающее Яблоко", "price": 350},
    {"name": "HOT SPOT Освежающий Ананас", "price": 350},
    {"name": "HOT SPOT Освежающий Арбуз", "price": 350},
    {"name": "HOT SPOT Персиковое Мороженое", "price": 350},
    {"name": "HUSKY MEDIUM Raspberry Forest Fruit", "price": 335},
    {"name": "HUSKY MEDIUM Indian Mango Ice", "price": 335},
    {"name": "HUSKY MEDIUM Cold Forest Fruit", "price": 335},
    {"name": "HUSKY MEDIUM Cold Watermelon Strawberry Honeydew", "price": 335},
    {"name": "HUSKY MEDIUM Cold Mango Ice Cream", "price": 335},
    {"name": "HUSKY MEDIUM Blueberry Lemonade Ice", "price": 335},
    {"name": "HUSKY MEDIUM Kiwi Pineapple Ice", "price": 335},
    {"name": "HUSKY MEDIUM Cold Blueberry Guava", "price": 335},
    {"name": "HUSKY MEDIUM Pomegranate Black Currant Ice", "price": 335},
    {"name": "HUSKY MEDIUM Tropic Mix Ice", "price": 335},
    {"name": "HUSKY MEDIUM Cold Watermelon Bubblegum", "price": 335},
    {"name": "HUSKY MEDIUM Cold Mango Citrus", "price": 335},
    {"name": "HUSKY MEDIUM Cold Lemon Grapefruit Orange", "price": 335},
    {"name": "HUSKY MEDIUM Cold Pineapple Lychee Banana", "price": 335},
    {"name": "HUSKY MEDIUM Sweet Melon Ice", "price": 335},
    {"name": "HUSKY MEDIUM Cold Strawberry Raspberry", "price": 335},
    {"name": "HUSKY MEDIUM Cold Pear Lychee", "price": 335},
    {"name": "HUSKY MEDIUM Raspberry Blackberry Ice", "price": 335},
    {"name": "HUSKY MEDIUM Cold Kiwi Strawberry Mint", "price": 335},
    {"name": "HUSKY MEDIUM Mango Grape Soda Ice", "price": 335},
    {"name": "HUSKY MEDIUM Blueberry Lemon Strawberry Ice", "price": 335},
    {"name": "HUSKY MEDIUM Cherry Apple Soda Ice", "price": 335},
    {"name": "HUSKY MEDIUM Lemon Yoghurt Ice", "price": 335},
    {"name": "HUSKY MEDIUM Cold Pineapple Mango Melon", "price": 335},
    {"name": "HUSKY MEDIUM Pineapple Coconut Ice", "price": 335},
    {"name": "HUSKY MEDIUM Cola Ice", "price": 335},
    {"name": "HUSKY MEDIUM Cold Energy Drink", "price": 335},
    {"name": "HUSKY MEDIUM Cold Honeydew Ice Cream", "price": 335},
    {"name": "HUSKY MEDIUM Cold Banana Strawberry Yogurt", "price": 335},
    {"name": "LYFT MEDIUM Ананас Кокос Лед", "price": 350},
    {"name": "LYFT MEDIUM Ананас Яблоко Лед", "price": 350},
    {"name": "LYFT MEDIUM Арбуз Дыня Лед", "price": 350},
    {"name": "LYFT MEDIUM Баббл Гам Лед", "price": 350},
    {"name": "LYFT MEDIUM Виноград Лед", "price": 350},
    {"name": "LYFT MEDIUM Джекфрут Каламанси Лед", "price": 350},
    {"name": "LYFT MEDIUM Дюшес Лед", "price": 350},
    {"name": "LYFT MEDIUM Клюква Лед", "price": 350},
    {"name": "LYFT MEDIUM Кола Вишня Лед", "price": 350},
    {"name": "LYFT MEDIUM Манго Персик Лед", "price": 350},
    {"name": "LYFT MEDIUM Ред Булл Лед", "price": 350},
    {"name": "LYFT MEDIUM Спрайт Лед", "price": 350},
    {"name": "LYFT MEDIUM Фанта Лед", "price": 350},
    {"name": "LYFT MEDIUM Фейхоа Лед", "price": 350},
    {"name": "LYFT MEDIUM Черника Ежевика Лед", "price": 350},
    {"name": "LYFT MEDIUM Юдзу Лед", "price": 350},
    {"name": "MOSMO Вишневый Сок", "price": 300},
    {"name": "MOSMO Дыня Черника", "price": 300},
    {"name": "MOSMO Кислая Вишня", "price": 300},
    {"name": "MOSMO Кислый Скитлс", "price": 300},
    {"name": "MOSMO Клубника Банан", "price": 300},
    {"name": "MOSMO Клубника Киви", "price": 300},
    {"name": "MOSMO Ледяной Виноград", "price": 300},
    {"name": "MOSMO Малиновый Лимонад", "price": 300},
    {"name": "MOSMO Морозные Лесные Ягоды", "price": 300},
    {"name": "MOSMO Морозный Ред Булл", "price": 300},
    {"name": "MOSMO Морс из Диких Ягод", "price": 300},
    {"name": "MOSMO Мохито Клубника", "price": 300},
    {"name": "MOSMO Смородиновый Лимонад", "price": 300},
    {"name": "MOSMO Сочный Персик", "price": 300},
    {"name": "MOSMO Черника Ежевика", "price": 300},
    {"name": "OXVA Арбузный Смузи", "price": 365},
    {"name": "OXVA Белый Помадный Виноград", "price": 365},
    {"name": "OXVA Вишневая Шипучка", "price": 365},
    {"name": "OXVA Вишня Персик и Лимонад", "price": 365},
    {"name": "OXVA Голубой Цитрус", "price": 365},
    {"name": "OXVA Киви Маракуйя Гуава", "price": 365},
    {"name": "OXVA Клубника Вишня и Малина", "price": 365},
    {"name": "OXVA Клубника и Арбуз", "price": 365},
    {"name": "OXVA Ледяной Ананас", "price": 365},
    {"name": "OXVA Лимон Лайм", "price": 365},
    {"name": "OXVA Манговый Апероль", "price": 365},
    {"name": "OXVA Микс Винограда", "price": 365},
    {"name": "OXVA Освежающая Дыня", "price": 365},
    {"name": "OXVA Пина Дайкири", "price": 365},
    {"name": "OXVA Райский Пунш", "price": 365},
    {"name": "OXVA Синяя Дымка", "price": 365},
    {"name": "OXVA Фруктовый Бум", "price": 365},
    {"name": "OXVA Черника Гранат", "price": 365},
    {"name": "OXVA Черника Малина", "price": 365},
    {"name": "PIXEL MEDIUM Баблгам", "price": 285},
    {"name": "PIXEL MEDIUM Бананово Клубничный Леденец", "price": 285},
    {"name": "PIXEL MEDIUM Вишня Йогурт", "price": 285},
    {"name": "PIXEL MEDIUM Груша Дюшес", "price": 285},
    {"name": "PIXEL MEDIUM Деревенская Вишня", "price": 285},
    {"name": "PIXEL MEDIUM Егермейстер", "price": 285},
    {"name": "PIXEL MEDIUM Клубничная Конфета", "price": 285},
    {"name": "PIXEL MEDIUM Клюквенный Морс", "price": 285},
    {"name": "PIXEL MEDIUM Кокосовое Печенье", "price": 285},
    {"name": "PIXEL MEDIUM Крымский Виноград", "price": 285},
    {"name": "PIXEL MEDIUM Лимонно Вишнёвый Леденец", "price": 285},
    {"name": "PIXEL MEDIUM Лимонный Леденец", "price": 285},
    {"name": "PIXEL MEDIUM Маунтин Дью", "price": 285},
    {"name": "PIXEL MEDIUM Мультифрукт", "price": 285},
    {"name": "PIXEL MEDIUM Мятная Жвачка", "price": 285},
    {"name": "PIXEL MEDIUM Пина Колада", "price": 285},
    {"name": "PIXEL MEDIUM Розовый Пляж", "price": 285},
    {"name": "PIXEL MEDIUM Сладкий Манго", "price": 285},
    {"name": "PIXEL MEDIUM Текила", "price": 285},
    {"name": "PIXEL MEDIUM Фанта", "price": 285},
    {"name": "PIXEL MEDIUM Черничный Йогурт", "price": 285},
    {"name": "PIXEL MEDIUM Чёрная Смородина", "price": 285},
    {"name": "PIXEL MEDIUM Энергетик", "price": 285},
    {"name": "SKALA V2 HARD Ананас со Льдом", "price": 335},
    {"name": "SKALA V2 HARD Барбарис со Льдом", "price": 335},
    {"name": "SKALA V2 HARD Вишня со Льдом", "price": 335},
    {"name": "SKALA V2 HARD Дыня со Льдом", "price": 335},
    {"name": "SKALA V2 HARD Ежевика со Льдом", "price": 335},
    {"name": "SKALA V2 HARD Земляника со Льдом", "price": 335},
    {"name": "SKALA V2 HARD Клубника со Льдом", "price": 335},
    {"name": "SKALA V2 HARD Клюква со Льдом", "price": 335},
    {"name": "SKALA V2 HARD Лесные Ягоды со Льдом", "price": 335},
    {"name": "SKALA V2 HARD Малина со Льдом", "price": 335},
    {"name": "SKALA V2 HARD Манго со Льдом", "price": 335},
    {"name": "SKALA V2 HARD Мульти Фрукт со Льдом", "price": 335},
    {"name": "SKALA V2 HARD Персик со Льдом", "price": 335},
    {"name": "SKALA V2 HARD Чёрная Смородина со Льдом", "price": 335},
    {"name": "SKALA V2 HARD Яблоко со Льдом", "price": 335},
    {"name": "SUBZERO MEDIUM Абрикос Земляника", "price": 350},
    {"name": "SUBZERO MEDIUM Ананас Кокос", "price": 350},
    {"name": "SUBZERO MEDIUM Арбузная Жвачка", "price": 350},
    {"name": "SUBZERO MEDIUM Банановый Коктейль", "price": 350},
    {"name": "SUBZERO MEDIUM Виноградное Уничтожение", "price": 350},
    {"name": "SUBZERO MEDIUM Вишневая Бомба", "price": 350},
    {"name": "SUBZERO MEDIUM Дыня", "price": 350},
    {"name": "SUBZERO MEDIUM Заряженный Энергетик", "price": 350},
    {"name": "SUBZERO MEDIUM Кислюшная Малина", "price": 350},
    {"name": "SUBZERO MEDIUM Клубничный Ананас", "price": 350},
    {"name": "SUBZERO MEDIUM Клубничный Персик", "price": 350},
    {"name": "SUBZERO MEDIUM Клюква Кизил", "price": 350},
    {"name": "SUBZERO MEDIUM Клюковка", "price": 350},
    {"name": "SUBZERO MEDIUM Кола Вишня", "price": 350},
    {"name": "SUBZERO MEDIUM Манго Маракуйя", "price": 350},
    {"name": "SUBZERO MEDIUM Ни Хуа Фейхоа", "price": 350},
    {"name": "SUBZERO MEDIUM Персик Маракуйя", "price": 350},
    {"name": "SUBZERO MEDIUM Съедобная Граната", "price": 350},
    {"name": "SUBZERO MEDIUM Фруктовое Фаталити", "price": 350},
    {"name": "SUBZERO MEDIUM Экстазная Груша", "price": 350},
    {"name": "SUBZERO MEDIUM Яблоко Киви", "price": 350},
    {"name": "SUBZERO MEDIUM Яблочный Пирог", "price": 350},
    {"name": "WAKA HARD Собираем миксом", "price": 500},
    {"name": "PHOBIA HARD Грейпфрут Маракуйя", "price": 350},
    {"name": "PHOBIA HARD Кола Лёд Лимон", "price": 350},
    {"name": "АНАРХИЯ V2 HARD", "price": 350},
    {"name": "МРАК Ананас Маракуйя", "price": 330},
    {"name": "МРАК Арбуз Малина", "price": 330},
    {"name": "МРАК Виноград Мята", "price": 330},
    {"name": "МРАК Двойное Яблоко", "price": 330},
    {"name": "МРАК Кислый Персик", "price": 330},
    {"name": "МРАК Клубничный Кекс", "price": 330},
    {"name": "МРАК Лимонные Леденцы", "price": 330},
    {"name": "МРАК Смородиновая Ронда", "price": 330},
    {"name": "МРАК Спрайт", "price": 330},
    {"name": "МРАК Фруктовые Пластинки", "price": 330},
]
